title: Tarik Brown # your name (or website title) here
logo: "/images/avatar.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Sophomore Computer Science Major and Public Policy Minor at the University of Notre Dame.
  My passions are Technology, Public Service, Anime and Jazz Music in no particular order.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/tarik-brown-hello/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
